apiVersion: v1
kind: Service
metadata:
  name: node-sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-sample-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000