apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-sample-app
  template:
    metadata:
      labels:
        app: node-sample-app
    spec:
      containers:
        - name: node-sample-app
          image: zeizz/node-sample-app
          ports:
            - containerPort: 3000
